### ISSUE TITLE
Network is unreachable

### ISSUE THREAD

**Issue by fenghuawei** [MesihK/prost#1] opened 2023-03-14 13:54 UTC
hello, i use prost makedb, error is urlib.error,URLErroe Network is unreachable   . I use ubuntu . I am in china .  Then I try VPN in windows,also the same error. what is the reseason? If Network is the reseason, is there altenative to overcome it ? Thanks

**Comment by MesihK** [comment] 2023-03-15 01:35
Hi fenghuawei , 

Thanks for the notification of the network issue! I'll try to use GitHub release assets in the next release so all the required binaries can be downloaded from GitHub which I assume accessible for you. I'm planning to do this in coming days. 

Thank you for trying PROST and I'll update it soon!
Best,
Mesih

**Comment by MesihK** [comment] 2023-04-21 21:48
Hi fenghuawei,

The issue is fixed on the release v0.2.7 and onward. Now the files are downloaded from GitHub.  Please feel free to open another issue if you still have problems.

Best,
Mesih

**Closed as completed by MesihK** 2023-04-21 21:48 UTC

**Comment by fenghuawei** [comment] 2023-05-04 02:33
Thanks very much.
----- 原始邮件 -----
发件人：Mesih Kılınç ***@***.***>
收件人：MesihK/prost ***@***.***>
抄送人：fenghuawei ***@***.***>,  Author ***@***.***>
主题：Re: [MesihK/prost] Network is unreachable (Issue #1)
日期：2023年04月22日 05点48分


Closed #1 as completed.
